version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:17.0.4'
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Download and Install Android SDK
          command: |
            sudo mkdir -p /usr/local/android-sdk-linux
            wget -q https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
            unzip -q commandlinetools-linux-6858069_latest.zip -d /usr/local/android-sdk-linux
            rm commandlinetools-linux-6858069_latest.zip
            echo 'export ANDROID_HOME="/usr/local/android-sdk-linux"' >> $BASH_ENV
            echo 'export PATH="$ANDROID_HOME/cmdline-tools/tools/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Accept Android licenses
          command: yes | sdkmanager --licenses
      - run:
          name: Set Android SDK Location
          command: echo "sdk.dir=/usr/local/android-sdk-linux" > /home/circleci/project/local.properties
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file
