version: 2.1
 
orbs:
  android: circleci/android@0.2.1
 
jobs:
  build:
    docker:
      - image: 'cimg/openjdk:17.0.4'
    environment:
      # Set environment variables for Android SDK
      ANDROID_HOME: "/home/circleci/android-sdk"
      ANDROID_SDK_ROOT: $ANDROID_HOME
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Install Android SDK Tools
          command: |
            mkdir -p $ANDROID_HOME
            wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
            unzip commandlinetools-linux-6858069_latest.zip -d $ANDROID_HOME
            yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --licenses
            $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platform-tools" "build-tools;30.0.2" "platforms;android-30" "extras;android;m2repository"
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file
